import os
import re
import time

import git

# Autogenerated filename
GUI_GENERIC_CODE = os.path.join(
    os.path.dirname(__file__),
    'gui_anonymiser_main.py',
)


def generate_version_information():
    """ Generate the version token and the date taken for this repository. """
    # Get repo information
    try:
        repo = git.Repo(search_parent_directories=True)
        sha = repo.head.object.hexsha
    except Exception:
        sha = 'none'

    date = time.strftime("%Y-%m-%dT%H:%M:%S%z", time.gmtime())

    return date, sha


if __name__ == '__main__':
    if os.path.exists(GUI_GENERIC_CODE):
        date, sha = generate_version_information()
        parameter_values_dict = {'BUILD_DATE': date, 'COMMIT_HASH': sha}
        # Read the GUI ui script
        content = open(GUI_GENERIC_CODE, 'r').read()

        # Substitute the placeholders
        content = re.sub(
            r"<(\w+?)>",
            lambda match: parameter_values_dict[match.group(1)],
            content,
        )

        # Overwrite the GUI ui script
        open(GUI_GENERIC_CODE, 'w').write(content)

    else:
        exit(1)
